"""Brand name -> website domain table for key-free logo resolution.

Used when an OSM feature has no ``website`` tag: we look up the brand/name here,
then fetch the brand's favicon via DuckDuckGo (no API key). Keep entries to
well-known chains where the domain-to-logo mapping is reliable.
"""
from __future__ import annotations

import re

BRAND_DOMAIN = {
    # quick service / food
    "mcdonalds": "mcdonalds.com",
    "mcdonald": "mcdonalds.com",
    "burger king": "bk.com",
    "wendys": "wendys.com",
    "subway": "subway.com",
    "taco bell": "tacobell.com",
    "kfc": "kfc.com",
    "chipotle": "chipotle.com",
    "dominos": "dominos.com",
    "dominos pizza": "dominos.com",
    "pizza hut": "pizzahut.com",
    "dunkin": "dunkindonuts.com",
    "dunkin donuts": "dunkindonuts.com",
    "starbucks": "starbucks.com",
    "chick fil a": "chick-fil-a.com",
    "panera bread": "panerabread.com",
    "arbys": "arbys.com",
    "sonic": "sonicdrivein.com",
    "sonic drive in": "sonicdrivein.com",
    "five guys": "fiveguys.com",
    "popeyes": "popeyesuk.com",
    "popeyes louisiana kitchen": "popeyesuk.com",
    "panda express": "pandaexpress.com",
    "jamba": "jamba.com",
    "jamba juice": "jamba.com",
    "shake shack": "shakeshack.com",
    "cava": "cava.com",
    "chilis": "chilis.com",
    "chili s": "chilis.com",
    "jersey mikes": "jerseymikes.com",
    "jersey mike s": "jerseymikes.com",
    "jack in the box": "jackinthebox.com",
    "ihop": "ihop.com",
    # coffee / convenience
    "dutch bros": "dutchbros.com",
    "tim hortons": "timhortons.com",
    "7 eleven": "7-eleven.com",
    "7eleven": "7-eleven.com",
    "circle k": "circlek.com",
    "caseys": "caseys.com",
    "caseys general store": "caseys.com",
    "speedway": "speedway.com",
    "quiktrip": "quiktrip.com",
    "wawa": "wawa.com",
    "cumberland farms": "cumberlandfarms.com",
    # grocery / retail
    "walmart": "walmart.com",
    "wal mart": "walmart.com",
    "walmart supercenter": "walmart.com",
    "target": "target.com",
    "kroger": "kroger.com",
    "aldi": "aldi.com",
    "albertsons": "albertsons.com",
    "safeway": "safeway.com",
    "publix": "publix.com",
    "wegmans": "wegmans.com",
    "whole foods": "wholefoodsmarket.com",
    "whole foods market": "wholefoodsmarket.com",
    "trader joes": "traderjoes.com",
    "costco": "costco.com",
    "sams club": "samsclub.com",
    "home depot": "homedepot.com",
    "lowes": "lowes.com",
    "menards": "menards.com",
    "tractor supply": "tractorsupply.com",
    "dollar general": "dollargeneral.com",
    "dollar tree": "dollartree.com",
    "family dollar": "familydollar.com",
    "nordstrom": "nordstrom.com",
    "zara": "zara.com",
    "lego": "lego.com",
    "vans": "vans.com",
    "banana republic": "bananarepublic.com",
    "victorias secret": "victoriassecret.com",
    "victoria s secret": "victoriassecret.com",
    "forever 21": "forever21.com",
    "j crew": "jcrew.com",
    "jcrew": "jcrew.com",
    "h m": "hm.com",
    "hm": "hm.com",
    "urban outfitters": "urbanoutfitters.com",
    "anthropologie": "anthropologie.com",
    "west elm": "westelm.com",
    "tommy bahama": "tommybahama.com",
    "dicks sporting goods": "dickssportinggoods.com",
    "dick s sporting goods": "dickssportinggoods.com",
    "gamestop": "gamestop.com",
    "barnes noble": "barnesandnoble.com",
    "barnes and noble": "barnesandnoble.com",
    "buckle": "buckle.com",
    "golden goose": "goldengoose.com",
    "tory burch": "toryburch.com",
    "gucci": "gucci.com",
    "tiffany company": "tiffany.com",
    "tiffany and company": "tiffany.com",
    "tiffany co": "tiffany.com",
    "louis vuitton": "louisvuitton.com",
    "david yurman": "davidyurman.com",
    "michael kors": "michaelkors.com",
    "bluemercury": "bluemercury.com",
    "blue mercury": "bluemercury.com",
    "the cheesecake factory": "thecheesecakefactory.com",
    "cheesecake factory": "thecheesecakefactory.com",
    "james avery": "jamesavery.com",
    "james avery jewelry": "jamesavery.com",
    "stonebriar centre": "shopstonebriar.com",
    "stonebriar center": "shopstonebriar.com",
    "northpark center": "northparkcenter.com",
    # pharmacy
    "walgreens": "walgreens.com",
    "cvs": "cvs.com",
    "cvs pharmacy": "cvs.com",
    "rite aid": "riteaid.com",
    # fuel
    "shell": "shell.com",
    "chevron": "chevron.com",
    "exxon": "corporate.exxonmobil.com",
    "exxonmobil": "corporate.exxonmobil.com",
    "mobil": "mobil.com",
    "bp": "bp.com",
    "valero": "valero.com",
    "marathon": "marathonpetroleum.com",
    "philips 66": "phillips66.com",
    "love s travel stops": "loves.com",
    "loves": "loves.com",
    # banking / shipping / fitness
    "bank of america": "bankofamerica.com",
    "wells fargo": "wellsfargo.com",
    "chase": "chase.com",
    "jpmorgan chase": "chase.com",
    "us bank": "usbank.com",
    "pnc bank": "pnc.com",
    "truist": "truist.com",
    "fedex": "fedex.com",
    "fedex office": "fedex.com",
    "ups": "ups.com",
    "planet fitness": "planetfitness.com",
    "anytime fitness": "anytimefitness.com",
    "la fitness": "lafitness.com",
    "amc": "amctheatres.com",
    "amc theatres": "amctheatres.com",
    "amc theaters": "amctheatres.com",
    "amc northpark 15": "amctheatres.com",
    "amc stonebriar 24": "amctheatres.com",
    "tesla": "tesla.com",
    "apple": "apple.com",
    "apple store": "apple.com",
    "liberty mutual": "libertymutual.com",
    "peloton": "onepeloton.com",
    "rolex": "rolex.com",
    # automotive
    "jiffy lube": "jiffylube.com",
    "meineke": "meineke.com",
    "autozone": "autozone.com",
    "advanced auto parts": "advanceautoparts.com",
    "advance auto parts": "advanceautoparts.com",
    "oreilly auto parts": "oreillyauto.com",
    "o reilly auto parts": "oreillyauto.com",
}


def normalize(text: str) -> str:
    """Lowercase, strip punctuation/possessives, collapse whitespace."""
    if not text:
        return ""
    t = text.lower()
    t = t.replace("'", "")  # "Wendy's" -> "wendys"
    t = re.sub(r"[^a-z0-9 ]+", " ", t)
    t = re.sub(r"\s+", " ", t).strip()
    return t


def domain_for_brand(brand: str, name: str) -> str:
    """Return a known domain for a brand/name, or empty string if unknown."""
    key = normalize(brand) or normalize(name)
    return BRAND_DOMAIN.get(key, "")
